// Copyright © 2023-2026 Vitaly Kuzyaev. All rights reserved.
// This file is part of the HaloUI project.
// Licensed under the GNU Affero General Public License v3.0.

namespace HaloUI.Enums;

public enum TextFieldAutocomplete
{
    Off,
    On,
    Name,
    HonorificPrefix,
    GivenName,
    AdditionalName,
    FamilyName,
    Nickname,
    Email,
    Username,
    NewPassword,
    CurrentPassword,
    OneTimeCode,
    OrganizationTitle,
    Organization,
    StreetAddress,
    AddressLine1,
    AddressLine2,
    AddressLine3,
    AddressLevel1,
    AddressLevel2,
    AddressLevel3,
    AddressLevel4,
    Country,
    CountryName,
    PostalCode,
    CreditCardName,
    CreditCardGivenName,
    CreditCardAdditionalName,
    CreditCardFamilyName,
    CreditCardNumber,
    CreditCardExpiration,
    CreditCardExpirationMonth,
    CreditCardExpirationYear,
    CreditCardSecurityCode,
    CreditCardType,
    TransactionCurrency,
    TransactionAmount,
    Language,
    Birthday,
    BirthdayDay,
    BirthdayMonth,
    BirthdayYear,
    Sex,
    Url,
    Photo,
    Telephone,
    TelephoneCountryCode,
    TelephoneNational,
    TelephoneAreaCode,
    TelephoneLocal,
    TelephoneExtension,
    Impp,
    Search
}