using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace HaloUI.ThemeSdk.Generators.Emitters;

internal static class ThemeHotSwapEmitter
{
    internal static void EmitThemeHotSwap(SourceProductionContext context)
    {
        var builder = new StringBuilder();
        ThemeSdkGenerator.AppendGeneratedHeader(builder);
        builder.AppendLine("#pragma warning disable CS8601");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.IO;");
        builder.AppendLine("using System.Text.Json;");
        builder.AppendLine("using HaloUI.Services;");
        builder.AppendLine("using HaloUI.Theme;");
        builder.AppendLine("using HaloUI.Theme.Sdk.Runtime;");
        builder.AppendLine("using HaloUI.Theme.Tokens;");
        builder.AppendLine("using HaloUI.Theme.Tokens.Brand;");
        builder.AppendLine("using HaloUI.Theme.Tokens.Generation;");
        builder.AppendLine();
        builder.Append("namespace ");
        builder.Append(ThemeSdkGenerator.RootNamespace);
        builder.AppendLine(".HotSwap;");
        builder.AppendLine();
        builder.AppendLine("internal static class ThemeHotSwap");
        builder.AppendLine("{");
        builder.AppendLine("    private static readonly JsonSerializerOptions ManifestSerializerOptions = new() { PropertyNameCaseInsensitive = true };");
        builder.AppendLine();
        builder.AppendLine("    internal static DesignTokenManifest ReadManifest(string json)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(json);");
        builder.AppendLine("        var manifest = JsonSerializer.Deserialize<DesignTokenManifest>(json, ManifestSerializerOptions);");
        builder.AppendLine("        if (manifest is null)");
        builder.AppendLine("        { ");
        builder.AppendLine("            throw new InvalidOperationException(\"Unable to deserialize design token manifest.\");");
        builder.AppendLine("        }");
        builder.AppendLine("        return manifest;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal static DesignTokenManifest ReadManifest(Stream stream)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(stream);");
        builder.AppendLine("        var manifest = JsonSerializer.Deserialize<DesignTokenManifest>(stream, ManifestSerializerOptions);");
        builder.AppendLine("        if (manifest is null)");
        builder.AppendLine("        { ");
        builder.AppendLine("            throw new InvalidOperationException(\"Unable to deserialize design token manifest.\");");
        builder.AppendLine("        }");
        builder.AppendLine("        return manifest;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal static void ApplyManifest(string json) => ApplyManifest(ReadManifest(json));");
        builder.AppendLine();
        builder.AppendLine("    internal static void ApplyManifest(DesignTokenManifest manifest)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(manifest);");
        builder.AppendLine("        DesignTokenManifestLoader.OverrideManifest(manifest);");
        builder.AppendLine("        DesignTokenSystem.ReloadThemes();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal static void ResetManifest()");
        builder.AppendLine("    {");
        builder.AppendLine("        DesignTokenManifestLoader.ResetOverride();");
        builder.AppendLine("        DesignTokenSystem.ReloadThemes();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    internal static bool TryHotSwapTheme(ThemeState themeState, string themeKey, Func<HaloTheme, HaloTheme>? configure = null)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (themeState is null)");
        builder.AppendLine("        { ");
        builder.AppendLine("            throw new ArgumentNullException(nameof(themeState));");
        builder.AppendLine("        }");
        builder.AppendLine("        if (string.IsNullOrWhiteSpace(themeKey))");
        builder.AppendLine("        { ");
        builder.AppendLine("            throw new ArgumentException(\"Theme key must be provided.\", nameof(themeKey));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        if (!TryResolveTheme(themeKey, out var baseTheme))");
        builder.AppendLine("        {");
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        if (configure is not null)");
        builder.AppendLine("        {");
        builder.AppendLine("            baseTheme = configure(baseTheme);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        themeState.SetTheme(themeKey, baseTheme);");
        builder.AppendLine("        return true;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static bool TryResolveTheme(string themeKey, out HaloTheme theme)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (DesignTokenPresets.All.TryGetValue(themeKey, out var preset) && preset is not null)");
        builder.AppendLine("        {");
        builder.AppendLine("            theme = new HaloTheme { Tokens = preset };");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        if (DesignTokenSystem.Themes.TryGetValue(themeKey, out var system) && system is not null)");
        builder.AppendLine("        {");
        builder.AppendLine("            theme = new HaloTheme { Tokens = system };");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        if (TryResolveBrandedTheme(themeKey, out var branded))");
        builder.AppendLine("        {");
        builder.AppendLine("            theme = new HaloTheme { Tokens = branded };");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        theme = default!;");
        builder.AppendLine("        return false;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static bool TryResolveBrandedTheme(string themeKey, out DesignTokenSystem system)");
        builder.AppendLine("    {");
        builder.AppendLine("        var separatorIndex = themeKey.IndexOf('-', StringComparison.Ordinal);");
        builder.AppendLine("        if (separatorIndex <= 0 || separatorIndex >= themeKey.Length - 1)");
        builder.AppendLine("        {");
        builder.AppendLine("            system = default!;");
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        var brandKey = themeKey[..separatorIndex];");
        builder.AppendLine("        var baseKey = themeKey[(separatorIndex + 1)..];");
        builder.AppendLine();
        builder.AppendLine("        if (!TryResolveThemeSystem(baseKey, out var baseSystem))");
        builder.AppendLine("        {");
        builder.AppendLine("            system = default!;");
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        if (!IsBrandDefined(brandKey, out var resolvedBrandKey))");
        builder.AppendLine("        {");
        builder.AppendLine("            system = default!;");
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        var brand = ThemeSystemRuntime.GetBrandTokens(resolvedBrandKey);");
        builder.AppendLine("        system = ThemeSystemRuntime.WithBrand(baseSystem, brand);");
        builder.AppendLine("        return true;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static bool TryResolveThemeSystem(string key, out DesignTokenSystem system)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (DesignTokenPresets.All.TryGetValue(key, out system) && system is not null)");
        builder.AppendLine("        {");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        if (DesignTokenSystem.Themes.TryGetValue(key, out system) && system is not null)");
        builder.AppendLine("        {");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        system = default!;");
        builder.AppendLine("        return false;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static bool IsBrandDefined(string brandKey, out string resolvedKey)");
        builder.AppendLine("    {");
        builder.AppendLine("        var manifest = DesignTokenManifestLoader.GetManifest();");
        builder.AppendLine("        foreach (var entry in manifest.Brands)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (string.Equals(entry.Key, brandKey, StringComparison.OrdinalIgnoreCase))");
        builder.AppendLine("            {");
        builder.AppendLine("                resolvedKey = entry.Key;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        if (string.Equals(brandKey, BrandTokens.HaloUI.Identity.Name, StringComparison.OrdinalIgnoreCase))");
        builder.AppendLine("        {");
        builder.AppendLine("            resolvedKey = BrandTokens.HaloUI.Identity.Name;");
        builder.AppendLine("            return true;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        resolvedKey = brandKey;");
        builder.AppendLine("        return false;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine("#pragma warning restore CS8601");

        context.AddSource("ThemeHotSwap.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
